# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCpaq0qm20UcAilo28w4Xuy1Zony2CMD
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
!{sys.executable} -m pip install mtcnn lz4 keras-facenet



import cv2 as cv
import os
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from PIL import Image, ImageEnhance
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# ────────────────────────────────────────────────────────────────
# Fonction d'augmentation
# ────────────────────────────────────────────────────────────────

def augment_face(face_img):
    """
    Génère des variantes d'un visage déjà cropé et redimensionné (160x160, RGB).
    Retourne une liste d'images numpy (inclut l'original).
    """
    augmented = [face_img]
    pil_img = Image.fromarray(face_img)

    # 1. Flip horizontal
    augmented.append(cv.flip(face_img, 1))

    # 2. Rotations légères
    h, w = face_img.shape[:2]
    center = (w // 2, h // 2)
    for angle in [-15, -8, 8, 15]:
        M = cv.getRotationMatrix2D(center, angle, 1.0)
        rotated = cv.warpAffine(face_img, M, (w, h),
                                borderMode=cv.BORDER_REFLECT)
        augmented.append(rotated)

    # 3. Variations de luminosité
    for factor in [0.6, 0.8, 1.2, 1.4]:
        bright = np.array(ImageEnhance.Brightness(pil_img).enhance(factor))
        augmented.append(bright)

    # 4. Variations de contraste
    for factor in [0.75, 1.25]:
        contrast = np.array(ImageEnhance.Contrast(pil_img).enhance(factor))
        augmented.append(contrast)

    # 5. Légère translation (±8px)
    for dx, dy in [(-8, 0), (8, 0), (0, -8), (0, 8)]:
        M_t = np.float32([[1, 0, dx], [0, 1, dy]])
        shifted = cv.warpAffine(face_img, M_t, (w, h),
                                borderMode=cv.BORDER_REFLECT)
        augmented.append(shifted)

    # Total : 1 + 1 + 4 + 4 + 2 + 4 = 16 variantes par photo
    return augmented

img=cv.imread("/content/drive/MyDrive/FACES/RUST COHLE/3cebcb4b85c65c234d72e006d6f9e17a.jpg")
img=cv.cvtColor(img,cv.COLOR_BGR2RGB)
plt.imshow(img)

from mtcnn.mtcnn import MTCNN
detector= MTCNN()
results= detector.detect_faces(img)

results

x,y,w,h=results[0]['box']
img=cv.rectangle(img,(x,y),(x+w,y+h),(0,0,255),10)
plt.imshow(img)

my_face=img[y:y+h,x:x+w,:]
my_face=cv.resize(my_face,(160,160))
plt.imshow(my_face)

my_face



class FACELOADING:
    def __init__(self, directory, augment=True):
        self.directory   = directory
        self.target_size = (160, 160)
        self.augment     = augment
        self.X = []
        self.Y = []
        self.detector = MTCNN()

    def extract_face(self, filename):
        img = cv.imread(filename)
        img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
        results = self.detector.detect_faces(img)
        if not results:
            raise ValueError(f"Aucun visage détecté dans {filename}")
        x, y, w, h = results[0]['box']
        x, y = abs(x), abs(y)
        face = img[y:y+h, x:x+w]
        face_arr = cv.resize(face, self.target_size)
        return face_arr

    def load_faces(self, dir):
        FACES = []
        for im_name in os.listdir(dir):
            try:
                path = dir + im_name
                face = self.extract_face(path)

                if self.augment:
                    variants = augment_face(face)
                    FACES.extend(variants)
                else:
                    FACES.append(face)

            except Exception as e:
                print(f"  ⚠ Ignoré ({im_name}) : {e}")
        return FACES

    def load_classes(self):
        for sub_dir in os.listdir(self.directory):
            path = self.directory + '/' + sub_dir + '/'
            FACES = self.load_faces(path)
            labels = [sub_dir for _ in range(len(FACES))]
            print(f"✅ {sub_dir} : {len(labels)} images (avec augmentation)")
            self.X.extend(FACES)
            self.Y.extend(labels)

        return np.asarray(self.X), np.asarray(self.Y)

    def plot_images(self):
        plt.figure(figsize=(16, 12))
        for num, image in enumerate(self.X):
            ncols = 6
            nrows = len(self.Y) // ncols + 1
            plt.subplot(nrows, ncols, num + 1)
            plt.imshow(image)
            plt.axis('off')

faceloading = FACELOADING("/content/drive/MyDrive/FACES", augment=True)
X, Y = faceloading.load_classes()

print(f"\n📊 Total images après augmentation : {len(X)}")
print(f"📊 Classes : {np.unique(Y)}")

faceloading.plot_images()

from keras_facenet import FaceNet
embedder = FaceNet()

def get_embedding(face_img):
  face_img = face_img.astype('float32')
  face_img = np.expand_dims(face_img, axis=0)
  return embedder.embeddings(face_img)[0]

print("\n⏳ Calcul des embeddings...")
EMBEDDED_X = np.asarray([get_embedding(img) for img in X])
print(f"✅ Embeddings calculés : {EMBEDDED_X.shape}")

np.savez_compressed('/content/drive/MyDrive/live facialrecognition/faces_embeddings_done_4classes.npz', EMBEDDED_X, Y)
print("💾 Embeddings sauvegardés.")

Y

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(Y)
Y_enc = encoder.transform(Y)

plt.plot(EMBEDDED_X[0])
plt.ylabel(Y[0])

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    EMBEDDED_X, Y_enc, shuffle=True, random_state=17, test_size=0.2
)

from sklearn.svm import SVC
model = SVC(kernel='linear', probability=True)
model.fit(X_train, Y_train)

ypreds_train = model.predict(X_train)
ypreds_test = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy_score(Y_train, ypreds_train)

accuracy_score(Y_test,ypreds_test)

t_im = cv.imread("/content/drive/MyDrive/966791e9dac816e4e1db1b7cf9874bf6.jpg")
t_im = cv.cvtColor(t_im, cv.COLOR_BGR2RGB)
x,y,w,h = detector.detect_faces(t_im)[0]['box']



t_im = t_im[y:y+h, x:x+w]
t_im = cv.resize(t_im, (160,160))
test_im = get_embedding(t_im)

test_im = [test_im]
ypreds = model.predict(test_im)

ypreds

encoder.inverse_transform(ypreds)

import pickle
#save the model
with open('/content/drive/MyDrive/live facialrecognition/svm_model_160x160.pkl','wb') as f:
    pickle.dump(model,f)

print("\n✅ Modèle sauvegardé : svm_model_160x160.pkl")

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(encoder, f)