# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIcJOA73Hsch4oKTD40KUO68DAi9jp8z
"""

# -*- coding: utf-8 -*-
"""
mnist_comparatif.py
-------------------
Compare k-NN, SVM et CNN sur le dataset MNIST.
Affiche un tableau récapitulatif des précisions et temps d'exécution.
À exécuter sur Google Colab.
"""

!pip install tensorflow scikit-learn

import time
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# ── 1. Chargement et prétraitement MNIST ───────────────────────────────────────
print("Chargement des données MNIST...")
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

# Pour k-NN et SVM : aplatir les images en vecteurs 784
x_train_flat = x_train.reshape(60000, -1).astype('float32') / 255
x_test_flat  = x_test.reshape(10000, -1).astype('float32') / 255

# Pour CNN : garder la forme 28x28x1
x_train_cnn = x_train.reshape(60000, 28, 28, 1).astype('float32') / 255
x_test_cnn  = x_test.reshape(10000, 28, 28, 1).astype('float32') / 255

# On utilise un sous-ensemble pour k-NN et SVM (trop lents sur 60 000 exemples)
N_TRAIN = 10000  # augmente si tu as le temps (max 60000)
N_TEST  = 2000

x_tr = x_train_flat[:N_TRAIN]
y_tr = y_train[:N_TRAIN]
x_te = x_test_flat[:N_TEST]
y_te = y_test[:N_TEST]

resultats = {}  # stocke les résultats pour le tableau final

# ── 2. k-NN ───────────────────────────────────────────────────────────────────
print("\n--- k-NN (k=3) ---")
t0 = time.time()
knn = KNeighborsClassifier(n_neighbors=3, n_jobs=-1)
knn.fit(x_tr, y_tr)
t_train_knn = time.time() - t0

t0 = time.time()
y_pred_knn = knn.predict(x_te)
t_test_knn = time.time() - t0

acc_knn = accuracy_score(y_te, y_pred_knn)
print(f"Précision : {acc_knn*100:.2f}%")
print(f"Temps entraînement : {t_train_knn:.2f}s | Temps inférence : {t_test_knn:.2f}s")
resultats['k-NN (k=3)'] = {
    'précision': f"{acc_knn*100:.2f}%",
    'temps_train': f"{t_train_knn:.2f}s",
    'temps_test': f"{t_test_knn:.2f}s",
    'données': f"{N_TRAIN} train / {N_TEST} test"
}

# ── 3. SVM ────────────────────────────────────────────────────────────────────
print("\n--- SVM (noyau RBF) ---")
t0 = time.time()
svm = SVC(kernel='rbf', C=5, gamma='scale')
svm.fit(x_tr, y_tr)
t_train_svm = time.time() - t0

t0 = time.time()
y_pred_svm = svm.predict(x_te)
t_test_svm = time.time() - t0

acc_svm = accuracy_score(y_te, y_pred_svm)
print(f"Précision : {acc_svm*100:.2f}%")
print(f"Temps entraînement : {t_train_svm:.2f}s | Temps inférence : {t_test_svm:.2f}s")
resultats['SVM (RBF)'] = {
    'précision': f"{acc_svm*100:.2f}%",
    'temps_train': f"{t_train_svm:.2f}s",
    'temps_test': f"{t_test_svm:.2f}s",
    'données': f"{N_TRAIN} train / {N_TEST} test"
}

# ── 4. CNN ────────────────────────────────────────────────────────────────────
print("\n--- CNN ---")
cnn = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])
cnn.compile(optimizer='adam',
            loss='sparse_categorical_crossentropy',
            metrics=['accuracy'])

t0 = time.time()
cnn.fit(x_train_cnn, y_train, epochs=5, batch_size=64,
        validation_split=0.1, verbose=1)
t_train_cnn = time.time() - t0

t0 = time.time()
test_loss, acc_cnn = cnn.evaluate(x_test_cnn, y_test, verbose=0)
t_test_cnn = time.time() - t0

print(f"Précision : {acc_cnn*100:.2f}%")
print(f"Temps entraînement : {t_train_cnn:.2f}s | Temps inférence : {t_test_cnn:.2f}s")
resultats['CNN'] = {
    'précision': f"{acc_cnn*100:.2f}%",
    'temps_train': f"{t_train_cnn:.2f}s",
    'temps_test': f"{t_test_cnn:.2f}s",
    'données': "60000 train / 10000 test"
}

# ── 5. Tableau récapitulatif ───────────────────────────────────────────────────
print("\n" + "="*65)
print(f"{'Algorithme':<15} {'Précision':>12} {'T. train':>12} {'T. test':>12}")
print("="*65)
for algo, res in resultats.items():
    print(f"{algo:<15} {res['précision']:>12} {res['temps_train']:>12} {res['temps_test']:>12}")
print("="*65)
print("\nNote : k-NN et SVM ont été évalués sur un sous-ensemble de")
print(f"{N_TRAIN} images d'entraînement et {N_TEST} images de test.")
print("Le CNN a été entraîné sur la totalité des 60 000 images.")

# Sauvegarde du modèle CNN
cnn.save('modele_cnn_mnist.h5')
print("\nModèle CNN sauvegardé : modele_cnn_mnist.h5")

# -*- coding: utf-8 -*-
"""
predire_chiffre.py
------------------
Charge le modèle CNN entraîné sur MNIST et prédit le chiffre
d'une image manuscrite uploadée sur Google Colab.
Affiche l'image originale, l'image prétraitée et le résultat.

Utilisation :
    1. Exécute ce script sur Google Colab
    2. Upload une photo de ton chiffre manuscrit quand demandé
"""

import numpy as np
import cv2
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from google.colab import files

# ── 1. Charger le modèle ───────────────────────────────────────────────────────
print("Chargement du modèle CNN...")
model = tf.keras.models.load_model('modele_cnn_mnist.h5')
print("Modèle chargé !\n")

# ── 2. Uploader l'image ────────────────────────────────────────────────────────
print("Uploade une image de chiffre manuscrit (fond blanc, chiffre noir)...")
uploaded = files.upload()
nom_fichier = list(uploaded.keys())[0]

# ── 3. Prétraitement ───────────────────────────────────────────────────────────
img_originale = cv2.imread(nom_fichier)
img_originale_rgb = cv2.cvtColor(img_originale, cv2.COLOR_BGR2RGB)

# Conversion en niveaux de gris
img_gris = cv2.cvtColor(img_originale, cv2.COLOR_BGR2GRAY)

# Redimensionnement 28x28
img_28 = cv2.resize(img_gris, (28, 28))

# Inversion des couleurs (MNIST = chiffre blanc sur fond noir)
img_invertie = img_28

# Normalisation
img_norm = img_invertie.astype('float32') / 255
img_input = img_norm.reshape(1, 28, 28, 1)

# ── 4. Prédiction ─────────────────────────────────────────────────────────────
prediction = model.predict(img_input, verbose=0)
chiffre = np.argmax(prediction)
confiance = np.max(prediction) * 100

# ── 5. Affichage ──────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(14, 5))
gs = gridspec.GridSpec(1, 3, figure=fig)

# Image originale
ax1 = fig.add_subplot(gs[0])
ax1.imshow(img_originale_rgb)
ax1.set_title("Image originale", fontsize=13, fontweight='bold')
ax1.axis('off')

# Image prétraitée (ce que le CNN voit)
ax2 = fig.add_subplot(gs[1])
ax2.imshow(img_invertie, cmap='gray')
ax2.set_title("Image vue par le CNN\n(28×28, inversée)", fontsize=13, fontweight='bold')
ax2.axis('off')

# Graphique des probabilités pour chaque chiffre
ax3 = fig.add_subplot(gs[2])
chiffres = list(range(10))
couleurs = ['#2ecc71' if i == chiffre else '#3498db' for i in chiffres]
bars = ax3.bar(chiffres, prediction[0] * 100, color=couleurs, edgecolor='white')
ax3.set_xlabel("Chiffre", fontsize=11)
ax3.set_ylabel("Confiance (%)", fontsize=11)
ax3.set_title("Probabilités par chiffre", fontsize=13, fontweight='bold')
ax3.set_xticks(chiffres)
ax3.set_ylim(0, 110)

# Annoter la barre gagnante
ax3.annotate(f"{confiance:.1f}%",
             xy=(chiffre, confiance),
             xytext=(chiffre, confiance + 4),
             ha='center', fontsize=11, fontweight='bold', color='#2ecc71')

plt.suptitle(
    f"Chiffre reconnu : {chiffre}   |   Confiance : {confiance:.2f}%",
    fontsize=15, fontweight='bold', color='#1a252f', y=1.02
)
plt.tight_layout()
plt.savefig('resultat_prediction.png', bbox_inches='tight', dpi=150)
plt.show()

print(f"\n Résultat : le modèle prédit le chiffre  {chiffre}  avec {confiance:.2f}% de confiance.")
print(f" Image sauvegardée : resultat_prediction.png")

# ── 6. Détail des probabilités ────────────────────────────────────────────────
print("\nDétail des probabilités :")
print("-" * 30)
for i, prob in enumerate(prediction[0]):
    barre = "█" * int(prob * 40)
    marqueur = " ← PRÉDIT" if i == chiffre else ""
    print(f"  {i} : {prob*100:5.2f}%  {barre}{marqueur}")
print("-" * 30)

# -*- coding: utf-8 -*-
"""
predire_plusieurs_chiffres.py
-----------------------------
Détecte et prédit automatiquement plusieurs chiffres sur une même image.
Fonctionne avec des images style MNIST (fond noir, chiffres blancs)
ou des photos réelles (fond blanc, chiffres noirs).

À exécuter sur Google Colab.
"""

import numpy as np
import cv2
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from google.colab import files

# ── 1. Charger le modèle ───────────────────────────────────────────────────────
print("Chargement du modèle CNN...")
model = tf.keras.models.load_model('modele_cnn_mnist.h5')
print("Modèle chargé !\n")

# ── 2. Uploader l'image ────────────────────────────────────────────────────────
print("Uploade ton image contenant les chiffres...")
uploaded = files.upload()
nom_fichier = list(uploaded.keys())[0]

# ── 3. Chargement et détection du type d'image ────────────────────────────────
img_originale = cv2.imread(nom_fichier)
img_originale_rgb = cv2.cvtColor(img_originale, cv2.COLOR_BGR2RGB)
img_gris = cv2.cvtColor(img_originale, cv2.COLOR_BGR2GRAY)

# Détection automatique : fond noir ou fond blanc ?
# Si la majorité des pixels est sombre → style MNIST (fond noir)
# Sinon → photo réelle (fond blanc)
moyenne = np.mean(img_gris)
fond_noir = moyenne < 127

if fond_noir:
    print("Image style MNIST détectée (fond noir, chiffres blancs)")
    img_binaire = cv2.threshold(img_gris, 50, 255, cv2.THRESH_BINARY)[1]
else:
    print("Photo réelle détectée (fond blanc, chiffres noirs)")
    img_binaire = cv2.adaptiveThreshold(
        img_gris, 255,
        cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv2.THRESH_BINARY_INV,
        blockSize=51, C=10
    )
    # Épaissir les traits fins
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    img_binaire = cv2.dilate(img_binaire, kernel, iterations=2)

# ── 4. Détection des contours de chaque chiffre ───────────────────────────────
contours, _ = cv2.findContours(img_binaire, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Filtrer les petits contours (bruit)
hauteur_img = img_binaire.shape[0]
contours_filtres = []
for cnt in contours:
    x, y, w, h = cv2.boundingRect(cnt)
    # Garder seulement les contours assez grands
    if h > hauteur_img * 0.2 and w > 5:
        contours_filtres.append((x, y, w, h))

# Trier de gauche à droite
contours_filtres = sorted(contours_filtres, key=lambda c: c[0])

print(f"\n{len(contours_filtres)} chiffre(s) détecté(s) !")

# ── 5. Prédiction pour chaque chiffre ─────────────────────────────────────────
resultats = []

for i, (x, y, w, h) in enumerate(contours_filtres):
    # Ajouter une marge autour du chiffre
    padding = int(max(w, h) * 0.2)
    x1 = max(0, x - padding)
    y1 = max(0, y - padding)
    x2 = min(img_binaire.shape[1], x + w + padding)
    y2 = min(img_binaire.shape[0], y + h + padding)

    # Extraire le chiffre
    chiffre_crop = img_binaire[y1:y2, x1:x2]

    # Rendre le crop carré
    ch, cw = chiffre_crop.shape
    taille = max(ch, cw)
    img_carree = np.zeros((taille, taille), dtype=np.uint8)
    offset_y = (taille - ch) // 2
    offset_x = (taille - cw) // 2
    img_carree[offset_y:offset_y+ch, offset_x:offset_x+cw] = chiffre_crop

    # Redimensionner en 28x28
    img_28 = cv2.resize(img_carree, (28, 28), interpolation=cv2.INTER_AREA)

    # Normaliser et prédire
    img_norm = img_28.astype('float32') / 255
    img_input = img_norm.reshape(1, 28, 28, 1)
    prediction = model.predict(img_input, verbose=0)
    chiffre_predit = np.argmax(prediction)
    confiance = np.max(prediction) * 100

    resultats.append({
        'position': (x1, y1, x2, y2),
        'chiffre': chiffre_predit,
        'confiance': confiance,
        'img_28': img_28,
        'prediction': prediction[0]
    })

# ── 6. Affichage des résultats ─────────────────────────────────────────────────
n = len(resultats)

# Figure 1 : image annotée avec les prédictions
fig1, ax = plt.subplots(1, 1, figsize=(14, 5))
ax.imshow(img_originale_rgb)
for r in resultats:
    x1, y1, x2, y2 = r['position']
    couleur = '#2ecc71' if r['confiance'] > 80 else '#e67e22' if r['confiance'] > 50 else '#e74c3c'
    rect = patches.Rectangle((x1, y1), x2-x1, y2-y1,
                               linewidth=2, edgecolor=couleur, facecolor='none')
    ax.add_patch(rect)
    ax.text(x1, y1 - 8, f"{r['chiffre']} ({r['confiance']:.0f}%)",
            color=couleur, fontsize=12, fontweight='bold',
            bbox=dict(boxstyle='round,pad=0.2', facecolor='black', alpha=0.6))
ax.set_title("Détection et reconnaissance des chiffres", fontsize=14, fontweight='bold')
ax.axis('off')
plt.tight_layout()
plt.savefig('detection_multiple.png', bbox_inches='tight', dpi=150)
plt.show()

# Figure 2 : détail de chaque chiffre
if n > 0:
    fig2, axes = plt.subplots(2, n, figsize=(n * 2, 5))
    if n == 1:
        axes = np.array([[axes[0]], [axes[1]]])

    for i, r in enumerate(resultats):
        # Ligne 1 : image 28x28
        axes[0][i].imshow(r['img_28'], cmap='gray')
        axes[0][i].set_title(f"Prédit : {r['chiffre']}\n{r['confiance']:.1f}%",
                              fontsize=10, fontweight='bold')
        axes[0][i].axis('off')

        # Ligne 2 : top 3 probabilités
        top3 = np.argsort(r['prediction'])[::-1][:3]
        couleurs_bar = ['#2ecc71', '#3498db', '#95a5a6']
        axes[1][i].barh([str(top3[j]) for j in range(3)],
                        [r['prediction'][top3[j]] * 100 for j in range(3)],
                        color=couleurs_bar)
        axes[1][i].set_xlim(0, 110)
        axes[1][i].tick_params(labelsize=9)

    fig2.suptitle("Détail par chiffre (image 28×28 + top 3 probabilités)",
                  fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig('detail_chiffres.png', bbox_inches='tight', dpi=150)
    plt.show()

# ── 7. Résumé textuel ─────────────────────────────────────────────────────────
print("\n" + "="*50)
print("  RÉSULTATS DE LA RECONNAISSANCE")
print("="*50)
sequence = ""
for i, r in enumerate(resultats):
    statut = "✓" if r['confiance'] > 80 else "~" if r['confiance'] > 50 else "✗"
    print(f"  Chiffre {i+1} : {r['chiffre']}  ({r['confiance']:.1f}%)  {statut}")
    sequence += str(r['chiffre'])
print(f"\n  Séquence lue : {' '.join(sequence)}")
print("="*50)
print("\n✓ = confiance > 80%  |  ~ = confiance 50-80%  |  ✗ = confiance < 50%")